name: dynamic_accordion
description: A dynamic list of accordion-style expansion tiles that allows users to seamlessly insert and remove items at specific indices.
version: 1.0.0
homepage: https://github.com/AlnasHossain/dynamic_accordion
repository: https://github.com/AlnasHossain/dynamic_accordion

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0