name: dynamic_accordion
description: A highly customizable Flutter widget that manages dynamic lists of ExpansionTiles, allowing users to insert, remove, and reorder sections on the fly.
version: 1.2.0
homepage: https://github.com/AlnasHossain/dynamic_accordion
repository: https://github.com/AlnasHossain/dynamic_accordion

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0